%YAML:1.0

# be cautious that whether the rosmsg of the image is compressed
if_compressed: false
image_topic: /camera/color/image_raw  

image_width: 640 
image_height: 480 
cam_fx: 603.95556640625
cam_fy: 603.1257934570312
cam_cx: 324.0858154296875
cam_cy: 232.72303771972656
cam_d0: 0.0
cam_d1: 0.0
cam_d2: 0.0
cam_d3: 0.0
cam_d4: 0.0

CameraExtrinsics:  # camera to imu
    time_offset: 0.000
    Trans: [0, 0, -0.16]
    Rot: [ 0.0,  1.0,  0.0,
           0.0,  0.0,  1.0, 
           1.0,  0.0,  0.0 ]