lidar0:
    topic: /velodyne_points
    is_livox: false
    Extrinsics:  #lidar to imu
        time_offset: 0.0
        Trans: [0.27255, -0.00053,0.17954]
        Rot: [1, 0, 0,
              0, 1, 0,
              0, 0, 1]
              
num_lidars: 1
lidar_timestamp_end: false  # if the timestamp of a lidar scan is set at the end of the scan

### FeatureExtraction ###
VLP16:  # Velodyne-VLP16
    N_SCAN: 32
    Horizon_SCAN: 1800
    point_filter_num: 4
    edge_threshold: 1.0
    surf_threshold: 0.1
    odometry_surface_leaf_size: 0.4
    min_distance: 0.5
    max_distance: 200.0

### Odometry ###
use_corner_feature: false
use_ivox: true # ikdtree ivox 精度与特征子图的分辨率正相关
ivox_filter_size_map_min: 0.5
current_scan_param:
    corner_leaf_size: 0.2
    surface_leaf_size: 0.5
    edge_min_valid_num: 10
    surf_min_valid_num: 200
    correspondence_downsample: 1 #2
keyframe_strategy:
    angle_degree: 10
    dist_meter: 1.0
    time_second: 10
map_param:    
    keyframe_search_radius: 50.0
    keyframe_search_time: 10.0
    keyframe_density: 2
    cloud_reserved_time: -1  # [s]