imu_topic: /imu_raw

imu_excite_threshold: 1.0  # statical initialization, do not move!s
gravity_mag: 9.80
if_normalized: false  # imu acc is normalized in FAST-LIVO dataset
if_use_init_bg: false
window_length: 2

IMUExtrinsics:  # imu to imu # garden.bag
    time_offset: 0.000
    Trans: [0, 0, 0]
    Rot: [ 0, -1, 0,
           1, 0, 0,
           0, 0,  1]
    # Rot: [ 1, 0, 0,
    #        0, 1, 0,
    #        0, 0,  1]